// Kho từ vựng cho trò "Nghe & chọn". Mỗi từ gồm emoji làm hình minh hoạ
// (luôn hiển thị được, không cần asset), từ tiếng Anh, và nghĩa tiếng Việt
// để khen/gợi ý. Nhóm theo chủ đề cho dễ quản lý — mỗi emoji là duy nhất.
// Thêm từ mới: chỉ cần thêm vào đúng nhóm bên dưới, không phải sửa code trò chơi.

export type Word = {
  en: string; // từ tiếng Anh (dùng cho câu lệnh + đọc)
  vi: string; // nghĩa tiếng Việt (khen ngợi/gợi ý)
  emoji: string;
};

export type Group = { key: string; label: string; words: Word[] };

export const GROUPS: Group[] = [
  {
    key: "animals",
    label: "Con vật",
    words: [
      { en: "turtle", vi: "con rùa", emoji: "🐢" },
      { en: "cat", vi: "con mèo", emoji: "🐱" },
      { en: "dog", vi: "con chó", emoji: "🐶" },
      { en: "rabbit", vi: "con thỏ", emoji: "🐰" },
      { en: "bear", vi: "con gấu", emoji: "🐻" },
      { en: "frog", vi: "con ếch", emoji: "🐸" },
      { en: "fish", vi: "con cá", emoji: "🐟" },
      { en: "bird", vi: "con chim", emoji: "🐦" },
      { en: "duck", vi: "con vịt", emoji: "🦆" },
      { en: "pig", vi: "con lợn", emoji: "🐷" },
      { en: "cow", vi: "con bò", emoji: "🐮" },
      { en: "lion", vi: "con sư tử", emoji: "🦁" },
      { en: "elephant", vi: "con voi", emoji: "🐘" },
      { en: "monkey", vi: "con khỉ", emoji: "🐵" },
      { en: "horse", vi: "con ngựa", emoji: "🐴" },
      { en: "tiger", vi: "con hổ", emoji: "🐯" },
      { en: "panda", vi: "gấu trúc", emoji: "🐼" },
      { en: "chicken", vi: "con gà", emoji: "🐔" },
      { en: "sheep", vi: "con cừu", emoji: "🐑" },
      { en: "mouse", vi: "con chuột", emoji: "🐭" },
      { en: "snake", vi: "con rắn", emoji: "🐍" },
      { en: "penguin", vi: "chim cánh cụt", emoji: "🐧" },
      { en: "owl", vi: "con cú", emoji: "🦉" },
      { en: "butterfly", vi: "con bướm", emoji: "🦋" },
      { en: "bee", vi: "con ong", emoji: "🐝" },
      { en: "dolphin", vi: "cá heo", emoji: "🐬" },
      { en: "octopus", vi: "bạch tuộc", emoji: "🐙" },
      { en: "crab", vi: "con cua", emoji: "🦀" },
      { en: "giraffe", vi: "hươu cao cổ", emoji: "🦒" },
      { en: "fox", vi: "con cáo", emoji: "🦊" },
      { en: "koala", vi: "gấu koala", emoji: "🐨" },
      { en: "zebra", vi: "ngựa vằn", emoji: "🦓" },
      { en: "snail", vi: "con ốc sên", emoji: "🐌" },
    ],
  },
  {
    key: "food",
    label: "Đồ ăn & thức uống",
    words: [
      { en: "apple", vi: "quả táo", emoji: "🍎" },
      { en: "banana", vi: "quả chuối", emoji: "🍌" },
      { en: "orange", vi: "quả cam", emoji: "🍊" },
      { en: "grapes", vi: "chùm nho", emoji: "🍇" },
      { en: "strawberry", vi: "quả dâu", emoji: "🍓" },
      { en: "watermelon", vi: "quả dưa hấu", emoji: "🍉" },
      { en: "pear", vi: "quả lê", emoji: "🍐" },
      { en: "lemon", vi: "quả chanh", emoji: "🍋" },
      { en: "cherry", vi: "quả anh đào", emoji: "🍒" },
      { en: "peach", vi: "quả đào", emoji: "🍑" },
      { en: "pineapple", vi: "quả dứa", emoji: "🍍" },
      { en: "coconut", vi: "quả dừa", emoji: "🥥" },
      { en: "tomato", vi: "quả cà chua", emoji: "🍅" },
      { en: "carrot", vi: "củ cà rốt", emoji: "🥕" },
      { en: "corn", vi: "bắp ngô", emoji: "🌽" },
      { en: "mushroom", vi: "cây nấm", emoji: "🍄" },
      { en: "bread", vi: "ổ bánh mì", emoji: "🍞" },
      { en: "cheese", vi: "phô mai", emoji: "🧀" },
      { en: "egg", vi: "quả trứng", emoji: "🥚" },
      { en: "cake", vi: "bánh kem", emoji: "🍰" },
      { en: "pizza", vi: "pizza", emoji: "🍕" },
      { en: "hamburger", vi: "bánh hamburger", emoji: "🍔" },
      { en: "hot dog", vi: "bánh xúc xích", emoji: "🌭" },
      { en: "fries", vi: "khoai tây chiên", emoji: "🍟" },
      { en: "popcorn", vi: "bỏng ngô", emoji: "🍿" },
      { en: "ice cream", vi: "kem", emoji: "🍦" },
      { en: "cookie", vi: "bánh quy", emoji: "🍪" },
      { en: "donut", vi: "bánh vòng", emoji: "🍩" },
      { en: "candy", vi: "cái kẹo", emoji: "🍬" },
      { en: "rice", vi: "bát cơm", emoji: "🍚" },
      { en: "noodles", vi: "bát mì", emoji: "🍜" },
      { en: "milk", vi: "hộp sữa", emoji: "🥛" },
      { en: "juice", vi: "hộp nước ép", emoji: "🧃" },
      { en: "water", vi: "giọt nước", emoji: "💧" },
    ],
  },
  {
    key: "colors",
    label: "Màu sắc",
    words: [
      { en: "red", vi: "màu đỏ", emoji: "🔴" },
      { en: "blue", vi: "màu xanh dương", emoji: "🔵" },
      { en: "green", vi: "màu xanh lá", emoji: "🟢" },
      { en: "yellow", vi: "màu vàng", emoji: "🟡" },
      { en: "orange", vi: "màu cam", emoji: "🟠" },
      { en: "purple", vi: "màu tím", emoji: "🟣" },
      { en: "brown", vi: "màu nâu", emoji: "🟤" },
      { en: "black", vi: "màu đen", emoji: "⚫" },
      { en: "pink", vi: "màu hồng", emoji: "🩷" },
    ],
  },
  {
    key: "numbers",
    label: "Số đếm",
    words: [
      { en: "one", vi: "số 1", emoji: "1️⃣" },
      { en: "two", vi: "số 2", emoji: "2️⃣" },
      { en: "three", vi: "số 3", emoji: "3️⃣" },
      { en: "four", vi: "số 4", emoji: "4️⃣" },
      { en: "five", vi: "số 5", emoji: "5️⃣" },
      { en: "six", vi: "số 6", emoji: "6️⃣" },
      { en: "seven", vi: "số 7", emoji: "7️⃣" },
      { en: "eight", vi: "số 8", emoji: "8️⃣" },
      { en: "nine", vi: "số 9", emoji: "9️⃣" },
      { en: "ten", vi: "số 10", emoji: "🔟" },
    ],
  },
  {
    key: "body",
    label: "Cơ thể",
    words: [
      { en: "hand", vi: "bàn tay", emoji: "✋" },
      { en: "foot", vi: "bàn chân", emoji: "🦶" },
      { en: "eye", vi: "con mắt", emoji: "👁️" },
      { en: "ear", vi: "cái tai", emoji: "👂" },
      { en: "nose", vi: "cái mũi", emoji: "👃" },
      { en: "mouth", vi: "cái miệng", emoji: "👄" },
      { en: "tooth", vi: "cái răng", emoji: "🦷" },
      { en: "tongue", vi: "cái lưỡi", emoji: "👅" },
    ],
  },
  {
    key: "clothes",
    label: "Quần áo",
    words: [
      { en: "shirt", vi: "áo thun", emoji: "👕" },
      { en: "pants", vi: "cái quần", emoji: "👖" },
      { en: "dress", vi: "cái váy", emoji: "👗" },
      { en: "shoes", vi: "đôi giày", emoji: "👟" },
      { en: "boots", vi: "đôi ủng", emoji: "🥾" },
      { en: "socks", vi: "đôi tất", emoji: "🧦" },
      { en: "cap", vi: "mũ lưỡi trai", emoji: "🧢" },
      { en: "gloves", vi: "găng tay", emoji: "🧤" },
      { en: "coat", vi: "áo khoác", emoji: "🧥" },
      { en: "scarf", vi: "khăn quàng", emoji: "🧣" },
    ],
  },
  {
    key: "school",
    label: "Đồ dùng học tập",
    words: [
      { en: "pencil", vi: "bút chì", emoji: "✏️" },
      { en: "pen", vi: "bút mực", emoji: "🖊️" },
      { en: "crayon", vi: "bút sáp màu", emoji: "🖍️" },
      { en: "paintbrush", vi: "cây cọ vẽ", emoji: "🖌️" },
      { en: "paints", vi: "hộp màu vẽ", emoji: "🎨" },
      { en: "scissors", vi: "cái kéo", emoji: "✂️" },
      { en: "ruler", vi: "thước kẻ", emoji: "📏" },
      { en: "notebook", vi: "quyển vở", emoji: "📓" },
      { en: "paper", vi: "tờ giấy", emoji: "📄" },
      { en: "backpack", vi: "ba lô", emoji: "🎒" },
    ],
  },
  {
    key: "toys",
    label: "Đồ chơi & đồ vật",
    words: [
      { en: "ball", vi: "quả bóng", emoji: "⚽" },
      { en: "car", vi: "ô tô", emoji: "🚗" },
      { en: "book", vi: "quyển sách", emoji: "📚" },
      { en: "balloon", vi: "quả bóng bay", emoji: "🎈" },
      { en: "kite", vi: "con diều", emoji: "🪁" },
      { en: "teddy bear", vi: "gấu bông", emoji: "🧸" },
      { en: "drum", vi: "cái trống", emoji: "🥁" },
      { en: "clock", vi: "đồng hồ", emoji: "⏰" },
      { en: "umbrella", vi: "cái ô", emoji: "☂️" },
      { en: "hat", vi: "cái mũ", emoji: "🎩" },
      { en: "key", vi: "chìa khoá", emoji: "🔑" },
      { en: "gift", vi: "hộp quà", emoji: "🎁" },
    ],
  },
  {
    key: "music",
    label: "Nhạc cụ",
    words: [
      { en: "guitar", vi: "đàn ghi-ta", emoji: "🎸" },
      { en: "piano", vi: "đàn piano", emoji: "🎹" },
      { en: "trumpet", vi: "cái kèn", emoji: "🎺" },
      { en: "violin", vi: "đàn vi-ô-lông", emoji: "🎻" },
      { en: "saxophone", vi: "kèn saxophone", emoji: "🎷" },
      { en: "microphone", vi: "cái micro", emoji: "🎤" },
    ],
  },
  {
    key: "nature",
    label: "Thiên nhiên",
    words: [
      { en: "sun", vi: "mặt trời", emoji: "☀️" },
      { en: "star", vi: "ngôi sao", emoji: "⭐" },
      { en: "moon", vi: "mặt trăng", emoji: "🌙" },
      { en: "tree", vi: "cái cây", emoji: "🌳" },
      { en: "flower", vi: "bông hoa", emoji: "🌸" },
      { en: "rose", vi: "hoa hồng", emoji: "🌹" },
      { en: "sunflower", vi: "hoa hướng dương", emoji: "🌻" },
      { en: "leaf", vi: "chiếc lá", emoji: "🍃" },
      { en: "cactus", vi: "cây xương rồng", emoji: "🌵" },
      { en: "palm tree", vi: "cây cọ", emoji: "🌴" },
      { en: "rainbow", vi: "cầu vồng", emoji: "🌈" },
      { en: "cloud", vi: "đám mây", emoji: "☁️" },
      { en: "mountain", vi: "ngọn núi", emoji: "⛰️" },
      { en: "wave", vi: "con sóng", emoji: "🌊" },
    ],
  },
  {
    key: "weather",
    label: "Thời tiết",
    words: [
      { en: "rain", vi: "trời mưa", emoji: "🌧️" },
      { en: "snow", vi: "bông tuyết", emoji: "❄️" },
      { en: "snowman", vi: "người tuyết", emoji: "☃️" },
      { en: "lightning", vi: "tia chớp", emoji: "⚡" },
      { en: "wind", vi: "cơn gió", emoji: "💨" },
      { en: "fog", vi: "sương mù", emoji: "🌫️" },
    ],
  },
  {
    key: "family",
    label: "Gia đình",
    words: [
      { en: "mom", vi: "mẹ", emoji: "👩" },
      { en: "dad", vi: "bố", emoji: "👨" },
      { en: "baby", vi: "em bé", emoji: "👶" },
      { en: "boy", vi: "bạn trai", emoji: "👦" },
      { en: "girl", vi: "bạn gái", emoji: "👧" },
      { en: "grandma", vi: "bà", emoji: "👵" },
      { en: "grandpa", vi: "ông", emoji: "👴" },
    ],
  },
  {
    key: "vehicles",
    label: "Phương tiện",
    words: [
      { en: "bus", vi: "xe buýt", emoji: "🚌" },
      { en: "train", vi: "tàu hoả", emoji: "🚆" },
      { en: "plane", vi: "máy bay", emoji: "✈️" },
      { en: "boat", vi: "con thuyền", emoji: "⛵" },
      { en: "ship", vi: "con tàu", emoji: "🚢" },
      { en: "bike", vi: "xe đạp", emoji: "🚲" },
      { en: "rocket", vi: "tên lửa", emoji: "🚀" },
      { en: "truck", vi: "xe tải", emoji: "🚚" },
      { en: "helicopter", vi: "trực thăng", emoji: "🚁" },
      { en: "taxi", vi: "xe taxi", emoji: "🚕" },
      { en: "police car", vi: "xe cảnh sát", emoji: "🚓" },
      { en: "fire truck", vi: "xe cứu hoả", emoji: "🚒" },
      { en: "ambulance", vi: "xe cứu thương", emoji: "🚑" },
      { en: "tractor", vi: "máy kéo", emoji: "🚜" },
    ],
  },
];

// Câu lệnh cho bé — dùng mạo từ "the" cho tự nhiên và dễ nghe.
export const PROMPTS = [
  (w: string) => `Touch the ${w}.`,
  (w: string) => `Find the ${w}.`,
  (w: string) => `Where is the ${w}?`,
  (w: string) => `Show me the ${w}.`,
];

// Toàn bộ từ, phẳng — tiện chọn hình gây nhiễu khác chủ đề.
export const ALL_WORDS: Word[] = GROUPS.flatMap((g) => g.words);
