// Kho từ vựng cho trò "Nghe & chọn" tiếng Trung. Mỗi từ gồm chữ Hán (đọc TTS),
// pinyin (chú thích nhỏ dưới câu lệnh), nghĩa tiếng Việt, và emoji làm hình.
// Emoji trong file là duy nhất. Thêm từ: chỉ cần thêm vào đúng nhóm bên dưới.

export type ZhWord = {
  hanzi: string;
  pinyin: string;
  vi: string;
  emoji: string;
};

export type Group = { key: string; label: string; words: ZhWord[] };

export const GROUPS: Group[] = [
  {
    key: "animals",
    label: "Con vật",
    words: [
      { hanzi: "乌龟", pinyin: "wūguī", vi: "con rùa", emoji: "🐢" },
      { hanzi: "猫", pinyin: "māo", vi: "con mèo", emoji: "🐱" },
      { hanzi: "狗", pinyin: "gǒu", vi: "con chó", emoji: "🐶" },
      { hanzi: "兔子", pinyin: "tùzi", vi: "con thỏ", emoji: "🐰" },
      { hanzi: "熊", pinyin: "xióng", vi: "con gấu", emoji: "🐻" },
      { hanzi: "青蛙", pinyin: "qīngwā", vi: "con ếch", emoji: "🐸" },
      { hanzi: "鱼", pinyin: "yú", vi: "con cá", emoji: "🐟" },
      { hanzi: "鸟", pinyin: "niǎo", vi: "con chim", emoji: "🐦" },
      { hanzi: "鸭子", pinyin: "yāzi", vi: "con vịt", emoji: "🦆" },
      { hanzi: "猪", pinyin: "zhū", vi: "con lợn", emoji: "🐷" },
      { hanzi: "牛", pinyin: "niú", vi: "con bò", emoji: "🐮" },
      { hanzi: "狮子", pinyin: "shīzi", vi: "con sư tử", emoji: "🦁" },
      { hanzi: "大象", pinyin: "dàxiàng", vi: "con voi", emoji: "🐘" },
      { hanzi: "猴子", pinyin: "hóuzi", vi: "con khỉ", emoji: "🐵" },
      { hanzi: "马", pinyin: "mǎ", vi: "con ngựa", emoji: "🐴" },
      { hanzi: "老虎", pinyin: "lǎohǔ", vi: "con hổ", emoji: "🐯" },
      { hanzi: "熊猫", pinyin: "xióngmāo", vi: "gấu trúc", emoji: "🐼" },
      { hanzi: "鸡", pinyin: "jī", vi: "con gà", emoji: "🐔" },
      { hanzi: "羊", pinyin: "yáng", vi: "con cừu", emoji: "🐑" },
      { hanzi: "老鼠", pinyin: "lǎoshǔ", vi: "con chuột", emoji: "🐭" },
      { hanzi: "蛇", pinyin: "shé", vi: "con rắn", emoji: "🐍" },
      { hanzi: "企鹅", pinyin: "qǐ'é", vi: "chim cánh cụt", emoji: "🐧" },
      { hanzi: "猫头鹰", pinyin: "māotóuyīng", vi: "con cú", emoji: "🦉" },
      { hanzi: "蝴蝶", pinyin: "húdié", vi: "con bướm", emoji: "🦋" },
      { hanzi: "蜜蜂", pinyin: "mìfēng", vi: "con ong", emoji: "🐝" },
      { hanzi: "海豚", pinyin: "hǎitún", vi: "cá heo", emoji: "🐬" },
      { hanzi: "螃蟹", pinyin: "pángxiè", vi: "con cua", emoji: "🦀" },
      { hanzi: "长颈鹿", pinyin: "chángjǐnglù", vi: "hươu cao cổ", emoji: "🦒" },
    ],
  },
  {
    key: "food",
    label: "Đồ ăn & thức uống",
    words: [
      { hanzi: "苹果", pinyin: "píngguǒ", vi: "quả táo", emoji: "🍎" },
      { hanzi: "香蕉", pinyin: "xiāngjiāo", vi: "quả chuối", emoji: "🍌" },
      { hanzi: "橙子", pinyin: "chéngzi", vi: "quả cam", emoji: "🍊" },
      { hanzi: "葡萄", pinyin: "pútáo", vi: "chùm nho", emoji: "🍇" },
      { hanzi: "草莓", pinyin: "cǎoméi", vi: "quả dâu", emoji: "🍓" },
      { hanzi: "西瓜", pinyin: "xīguā", vi: "quả dưa hấu", emoji: "🍉" },
      { hanzi: "梨", pinyin: "lí", vi: "quả lê", emoji: "🍐" },
      { hanzi: "柠檬", pinyin: "níngméng", vi: "quả chanh", emoji: "🍋" },
      { hanzi: "樱桃", pinyin: "yīngtáo", vi: "quả anh đào", emoji: "🍒" },
      { hanzi: "桃子", pinyin: "táozi", vi: "quả đào", emoji: "🍑" },
      { hanzi: "菠萝", pinyin: "bōluó", vi: "quả dứa", emoji: "🍍" },
      { hanzi: "西红柿", pinyin: "xīhóngshì", vi: "quả cà chua", emoji: "🍅" },
      { hanzi: "胡萝卜", pinyin: "húluóbo", vi: "củ cà rốt", emoji: "🥕" },
      { hanzi: "玉米", pinyin: "yùmǐ", vi: "bắp ngô", emoji: "🌽" },
      { hanzi: "蘑菇", pinyin: "mógū", vi: "cây nấm", emoji: "🍄" },
      { hanzi: "面包", pinyin: "miànbāo", vi: "ổ bánh mì", emoji: "🍞" },
      { hanzi: "奶酪", pinyin: "nǎilào", vi: "phô mai", emoji: "🧀" },
      { hanzi: "鸡蛋", pinyin: "jīdàn", vi: "quả trứng", emoji: "🥚" },
      { hanzi: "蛋糕", pinyin: "dàngāo", vi: "bánh kem", emoji: "🍰" },
      { hanzi: "比萨", pinyin: "bǐsà", vi: "pizza", emoji: "🍕" },
      { hanzi: "冰淇淋", pinyin: "bīngqílín", vi: "kem", emoji: "🍦" },
      { hanzi: "饼干", pinyin: "bǐnggān", vi: "bánh quy", emoji: "🍪" },
      { hanzi: "糖果", pinyin: "tángguǒ", vi: "cái kẹo", emoji: "🍬" },
      { hanzi: "米饭", pinyin: "mǐfàn", vi: "bát cơm", emoji: "🍚" },
      { hanzi: "面条", pinyin: "miàntiáo", vi: "bát mì", emoji: "🍜" },
      { hanzi: "牛奶", pinyin: "niúnǎi", vi: "hộp sữa", emoji: "🥛" },
      { hanzi: "果汁", pinyin: "guǒzhī", vi: "nước ép", emoji: "🧃" },
      { hanzi: "水", pinyin: "shuǐ", vi: "nước", emoji: "💧" },
    ],
  },
  {
    key: "colors",
    label: "Màu sắc",
    words: [
      { hanzi: "红色", pinyin: "hóngsè", vi: "màu đỏ", emoji: "🔴" },
      { hanzi: "蓝色", pinyin: "lánsè", vi: "màu xanh dương", emoji: "🔵" },
      { hanzi: "绿色", pinyin: "lǜsè", vi: "màu xanh lá", emoji: "🟢" },
      { hanzi: "黄色", pinyin: "huángsè", vi: "màu vàng", emoji: "🟡" },
      { hanzi: "橙色", pinyin: "chéngsè", vi: "màu cam", emoji: "🟠" },
      { hanzi: "紫色", pinyin: "zǐsè", vi: "màu tím", emoji: "🟣" },
      { hanzi: "棕色", pinyin: "zōngsè", vi: "màu nâu", emoji: "🟤" },
      { hanzi: "黑色", pinyin: "hēisè", vi: "màu đen", emoji: "⚫" },
      { hanzi: "粉色", pinyin: "fěnsè", vi: "màu hồng", emoji: "🩷" },
    ],
  },
  {
    key: "numbers",
    label: "Số đếm",
    words: [
      { hanzi: "一", pinyin: "yī", vi: "số 1", emoji: "1️⃣" },
      { hanzi: "二", pinyin: "èr", vi: "số 2", emoji: "2️⃣" },
      { hanzi: "三", pinyin: "sān", vi: "số 3", emoji: "3️⃣" },
      { hanzi: "四", pinyin: "sì", vi: "số 4", emoji: "4️⃣" },
      { hanzi: "五", pinyin: "wǔ", vi: "số 5", emoji: "5️⃣" },
      { hanzi: "六", pinyin: "liù", vi: "số 6", emoji: "6️⃣" },
      { hanzi: "七", pinyin: "qī", vi: "số 7", emoji: "7️⃣" },
      { hanzi: "八", pinyin: "bā", vi: "số 8", emoji: "8️⃣" },
      { hanzi: "九", pinyin: "jiǔ", vi: "số 9", emoji: "9️⃣" },
      { hanzi: "十", pinyin: "shí", vi: "số 10", emoji: "🔟" },
    ],
  },
  {
    key: "body",
    label: "Cơ thể",
    words: [
      { hanzi: "手", pinyin: "shǒu", vi: "bàn tay", emoji: "✋" },
      { hanzi: "脚", pinyin: "jiǎo", vi: "bàn chân", emoji: "🦶" },
      { hanzi: "眼睛", pinyin: "yǎnjing", vi: "con mắt", emoji: "👁️" },
      { hanzi: "耳朵", pinyin: "ěrduo", vi: "cái tai", emoji: "👂" },
      { hanzi: "鼻子", pinyin: "bízi", vi: "cái mũi", emoji: "👃" },
      { hanzi: "嘴巴", pinyin: "zuǐba", vi: "cái miệng", emoji: "👄" },
      { hanzi: "牙齿", pinyin: "yáchǐ", vi: "cái răng", emoji: "🦷" },
      { hanzi: "舌头", pinyin: "shétou", vi: "cái lưỡi", emoji: "👅" },
    ],
  },
  {
    key: "family",
    label: "Gia đình",
    words: [
      { hanzi: "妈妈", pinyin: "māma", vi: "mẹ", emoji: "👩" },
      { hanzi: "爸爸", pinyin: "bàba", vi: "bố", emoji: "👨" },
      { hanzi: "宝宝", pinyin: "bǎobao", vi: "em bé", emoji: "👶" },
      { hanzi: "男孩", pinyin: "nánhái", vi: "bạn trai", emoji: "👦" },
      { hanzi: "女孩", pinyin: "nǚhái", vi: "bạn gái", emoji: "👧" },
      { hanzi: "奶奶", pinyin: "nǎinai", vi: "bà", emoji: "👵" },
      { hanzi: "爷爷", pinyin: "yéye", vi: "ông", emoji: "👴" },
    ],
  },
  {
    key: "clothes",
    label: "Quần áo",
    words: [
      { hanzi: "衬衫", pinyin: "chènshān", vi: "áo sơ mi", emoji: "👕" },
      { hanzi: "裤子", pinyin: "kùzi", vi: "cái quần", emoji: "👖" },
      { hanzi: "裙子", pinyin: "qúnzi", vi: "cái váy", emoji: "👗" },
      { hanzi: "鞋子", pinyin: "xiézi", vi: "đôi giày", emoji: "👟" },
      { hanzi: "袜子", pinyin: "wàzi", vi: "đôi tất", emoji: "🧦" },
      { hanzi: "帽子", pinyin: "màozi", vi: "cái mũ", emoji: "🧢" },
      { hanzi: "手套", pinyin: "shǒutào", vi: "găng tay", emoji: "🧤" },
    ],
  },
  {
    key: "school",
    label: "Đồ dùng học tập",
    words: [
      { hanzi: "铅笔", pinyin: "qiānbǐ", vi: "bút chì", emoji: "✏️" },
      { hanzi: "钢笔", pinyin: "gāngbǐ", vi: "bút mực", emoji: "🖊️" },
      { hanzi: "蜡笔", pinyin: "làbǐ", vi: "bút sáp màu", emoji: "🖍️" },
      { hanzi: "剪刀", pinyin: "jiǎndāo", vi: "cái kéo", emoji: "✂️" },
      { hanzi: "尺子", pinyin: "chǐzi", vi: "thước kẻ", emoji: "📏" },
      { hanzi: "书", pinyin: "shū", vi: "quyển sách", emoji: "📚" },
      { hanzi: "书包", pinyin: "shūbāo", vi: "ba lô", emoji: "🎒" },
    ],
  },
  {
    key: "toys",
    label: "Đồ chơi & đồ vật",
    words: [
      { hanzi: "球", pinyin: "qiú", vi: "quả bóng", emoji: "⚽" },
      { hanzi: "气球", pinyin: "qìqiú", vi: "bóng bay", emoji: "🎈" },
      { hanzi: "风筝", pinyin: "fēngzheng", vi: "con diều", emoji: "🪁" },
      { hanzi: "玩具熊", pinyin: "wánjùxióng", vi: "gấu bông", emoji: "🧸" },
      { hanzi: "鼓", pinyin: "gǔ", vi: "cái trống", emoji: "🥁" },
      { hanzi: "钟", pinyin: "zhōng", vi: "đồng hồ", emoji: "⏰" },
      { hanzi: "伞", pinyin: "sǎn", vi: "cái ô", emoji: "☂️" },
      { hanzi: "钥匙", pinyin: "yàoshi", vi: "chìa khoá", emoji: "🔑" },
      { hanzi: "礼物", pinyin: "lǐwù", vi: "hộp quà", emoji: "🎁" },
    ],
  },
  {
    key: "music",
    label: "Nhạc cụ",
    words: [
      { hanzi: "吉他", pinyin: "jítā", vi: "đàn ghi-ta", emoji: "🎸" },
      { hanzi: "钢琴", pinyin: "gāngqín", vi: "đàn piano", emoji: "🎹" },
      { hanzi: "小号", pinyin: "xiǎohào", vi: "cái kèn", emoji: "🎺" },
      { hanzi: "小提琴", pinyin: "xiǎotíqín", vi: "đàn vi-ô-lông", emoji: "🎻" },
    ],
  },
  {
    key: "nature",
    label: "Thiên nhiên",
    words: [
      { hanzi: "太阳", pinyin: "tàiyáng", vi: "mặt trời", emoji: "☀️" },
      { hanzi: "星星", pinyin: "xīngxing", vi: "ngôi sao", emoji: "⭐" },
      { hanzi: "月亮", pinyin: "yuèliang", vi: "mặt trăng", emoji: "🌙" },
      { hanzi: "树", pinyin: "shù", vi: "cái cây", emoji: "🌳" },
      { hanzi: "花", pinyin: "huā", vi: "bông hoa", emoji: "🌸" },
      { hanzi: "叶子", pinyin: "yèzi", vi: "chiếc lá", emoji: "🍃" },
      { hanzi: "彩虹", pinyin: "cǎihóng", vi: "cầu vồng", emoji: "🌈" },
      { hanzi: "云", pinyin: "yún", vi: "đám mây", emoji: "☁️" },
      { hanzi: "山", pinyin: "shān", vi: "ngọn núi", emoji: "⛰️" },
      { hanzi: "海浪", pinyin: "hǎilàng", vi: "con sóng", emoji: "🌊" },
    ],
  },
  {
    key: "weather",
    label: "Thời tiết",
    words: [
      { hanzi: "雨", pinyin: "yǔ", vi: "trời mưa", emoji: "🌧️" },
      { hanzi: "雪", pinyin: "xuě", vi: "bông tuyết", emoji: "❄️" },
      { hanzi: "雪人", pinyin: "xuěrén", vi: "người tuyết", emoji: "☃️" },
      { hanzi: "闪电", pinyin: "shǎndiàn", vi: "tia chớp", emoji: "⚡" },
      { hanzi: "风", pinyin: "fēng", vi: "cơn gió", emoji: "💨" },
    ],
  },
  {
    key: "vehicles",
    label: "Phương tiện",
    words: [
      { hanzi: "汽车", pinyin: "qìchē", vi: "ô tô", emoji: "🚗" },
      { hanzi: "巴士", pinyin: "bāshì", vi: "xe buýt", emoji: "🚌" },
      { hanzi: "火车", pinyin: "huǒchē", vi: "tàu hoả", emoji: "🚆" },
      { hanzi: "飞机", pinyin: "fēijī", vi: "máy bay", emoji: "✈️" },
      { hanzi: "船", pinyin: "chuán", vi: "con thuyền", emoji: "⛵" },
      { hanzi: "自行车", pinyin: "zìxíngchē", vi: "xe đạp", emoji: "🚲" },
      { hanzi: "火箭", pinyin: "huǒjiàn", vi: "tên lửa", emoji: "🚀" },
      { hanzi: "卡车", pinyin: "kǎchē", vi: "xe tải", emoji: "🚚" },
      { hanzi: "直升机", pinyin: "zhíshēngjī", vi: "trực thăng", emoji: "🚁" },
      { hanzi: "出租车", pinyin: "chūzūchē", vi: "xe taxi", emoji: "🚕" },
    ],
  },
];

// Câu lệnh tiếng Trung cho bé — chèn chữ Hán vào chỗ ${w}.
export const PROMPTS = [
  (w: string) => `点一下${w}`,
  (w: string) => `找一找${w}`,
  (w: string) => `${w}在哪里？`,
  (w: string) => `指一指${w}`,
];

export const ALL_WORDS: ZhWord[] = GROUPS.flatMap((g) => g.words);
